### ISSUE TITLE
Resizing fails if Slim installed in subdirectory

### ISSUE THREAD

**Issue by mulhoon** [tuupola/slim-image-resize#1]
Hi,
I struggled to get this working first time becasue it was looking in the wrong place for the images.

I had to change **line 53** of `ImageResize.php` to...

``` php
$target   = $request->getRootUri().$request->getResourceUri();
```

was I doing something wrong?

**Comment by tuupola** [comment]
Difficult to say because I do not know what you were doing :) However I am using the middleware in production without any problems.

**Comment by mulhoon** [comment]
Thanks for the fast response.

It may be a Slim configuration issue. When I installed slim-image-resize afresh and tried the example it did the same, it was looking in the root. It's working for me with this line, so it's fine to close this, might be helpful for others when searching.

Oh, I also noticed that you can't include '-' in your image name because of the parameters, might be worth mentioning in the readme.

Great work BTW. Thanks for this.

**Comment by tuupola** [comment]
What version of Slim are you using?

**Comment by mulhoon** [comment]
The latest from the git repo (2.4.2 i think)

**Comment by tuupola** [comment]
Is you Slim application installed into a subdirectory or directly into webserver document root?

**Comment by mulhoon** [comment]
It's in a subdirectory.

**Comment by tuupola** [comment]
Can you upgrade to 0.6.1 and see if that fixes your problem. Also note that for caching to work when installed in subfolder, the .htaccess file should  be like following.

```
RewriteBase /example

# Check for cached image in cache folder.
RewriteCond %{REQUEST_METHOD} ^GET$
RewriteCond %{DOCUMENT_ROOT}/example/cache/%{REQUEST_URI} -f
RewriteRule ^(.*)$ /example/cache/example/$1 [L,QSA]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [QSA,L]
```

Above rules assumes your folder name is `example`.

**Comment by mulhoon** [comment]
Thanks! It wall works perfectly now.
